### ISSUE TITLE
The application does not work

### ISSUE THREAD

**Issue by harshbg** [Deffro/statify#1]
When I click on http://5d4a6818027f.ngrok.io/ it gives me the following error: 

**Failed to complete tunnel connection**

_The connection to http://5d4a6818027f.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:8080.

Make sure that a web service is running on localhost:8080 and that it is a valid address.

The error encountered was: dial tcp 127.0.0.1:8080: connect: connection refused_

**Comment by Deffro** [comment]
I deployed the app on [Heroku](https://statify-deffro.herokuapp.com/) and it works now.
